"""
2026-08-03

Spike Encoding / Decoding Schemes. 

Based on system in:
Schuman, C., Rizzo, C., McDonald-Carmack, J., Skuda, N., & Plank, J. (2022). 
Evaluating Encoding and Decoding Approaches for Spiking Neuromorphic Systems. 
Proceedings of the International Conference on Neuromorphic Systems 2022, 1–9. 
https://doi.org/10.1145/3546790.3546792

"""

import sys
from abc import ABC, abstractmethod
from typing import Literal, Sequence, Tuple

import numpy as np
from numpy.typing import ArrayLike
import gymnasium as gym

from common.base import SpikeCoder


ENCODER_DICT = {
    "single": 'SingleSpikeEncoder',
    "temporal": 'TemporalEncoder',
    "rate": 'RateEncoder',
    "multi": 'MultiSpikeEncoder'
}

DECODER_DICT = {
    "voting": 'SingleVotingDecoder',
    "weighted": 'WeightedVotingDecoder',
    "ttfs": 'TimeToFirstSpikeDecoder',
    "rate": 'RateDecoder',
    "rate-div": 'RateDivDecoder',
    "temporal": 'TemporalDecoder'
}


def create_spike_encoder(method: str, **kwargs):
    method = str(method).lower()
    if method not in ENCODER_DICT:
        raise ValueError(f"Encoder type: {method} not found in supported spike encoding methods")
    clss_name = ENCODER_DICT.get(method)
    clss = getattr(sys.modules[__name__], clss_name)
    return clss(**kwargs)

def create_spike_decoder(method: str, **kwargs):
    method = str(method).lower()
    if method not in DECODER_DICT:
        raise ValueError(f"Decoder type: {method} not found in supported spike decoding methods")
    clss_name = DECODER_DICT.get(method)
    clss = getattr(sys.modules[__name__], clss_name)
    return clss(**kwargs)


class CompositeSpikeCoder(SpikeCoder, ABC):
    def __init__(self, input_channels, output_channels, window_size, *,
                 encoding_method: Literal["single", "multi", "rate", "temporal"] = 'single',
                 encoder_params: dict = {},
                 decoding_method: Literal["voting", "weighted-voting", "rate", "rate-div", "temporal", "ttfs"] = 'voting',
                 decoder_params: dict = {},
                 ):
        super().__init__()
        self._window_size = window_size

        encoder_params["window_size"] = self.window_size
        decoder_params["window_size"] = self.window_size

        # Create separate Encoder and Decoder based on specifications
        self.encoder: BaseSpikeEncoder = create_spike_encoder(method=encoding_method, n_channels=input_channels,
                                                              **encoder_params)
        self.decoder: BaseSpikeDecoder = create_spike_decoder(method=decoding_method, out_channels=output_channels,
                                                              **decoder_params)

        self._input_neurons = self.encoder.neuron_size
        self._output_neurons = self.decoder.neuron_size

        ## Remove this after testing
        # self.window_size = window_size
        # self._input_neurons = input_channels
        # self._output_neurons = output_channels
        ##

        # Buffer to store encoded spike train to give network at each timestep (input buffer)
        #   and to record spikes generated by network for decoding at end of window (output buffer)
        self._input_buffer = np.zeros((self._input_neurons, self.window_size), dtype=np.int8)
        self._output_buffer = np.zeros((self._output_neurons, self.window_size), dtype=np.int8)

        # Step counter within window
        self._counter = 0

        # Flags and controls for effective flow
        self._window_start = True
        self._window_end = False
        self._encoder_called = False
        self._decoder_called = False

    def encode(self, inp: int | np.ndarray):
        # Control proper flow of encoder-decoder
        if (not self._decoder_called) and not self._window_start:
            raise RuntimeError("Decoder must be called before calling Encoder, unless it's a new window")
        self._decoder_called = False

        # If previous window just ended, clear buffer and reset counter
        if self._window_start:
            self._clear_buffer()
            self._counter = 0
            self._window_end = False

        # At beginning of window, encoder input values into spike trains, 
        #   then store in input buffer
        if self._window_start:
            self._validate_input(inp)
            spk_train = self.encoder.generate_spikes(inp)
            ## Remove this after testing
            # print(f"Encoding inputs {inp}")
            # spk_train = np.zeros((self._input_neurons, self.window_size), dtype=np.int8)
            # spk_train[::2, ::2] = 1
            # spk_train[1::2, 1::2] = 1
            ##
            self._input_buffer = spk_train
            self._window_start = False

        self._encoder_called = True

        return self._input_buffer[:, self._counter]

    def decode(self, spikes: np.ndarray) -> None | np.ndarray | int | float:
        # Control proper flow of encoder-decoder
        if not self._encoder_called:
            raise RuntimeError("Encoder must be called before calling Decoder")
        self._encoder_called = False

        # If still within window, record spikes onto output buffer
        if not self._window_end:
            # Record spikes
            self._output_buffer[:, self._counter] = spikes

        # Increment counter and check for end of window
        self._window_end = self._counter >= (self.window_size - 1)
        self._counter += 1

        # If window has ended, decode the output buffer into output values
        outp = None
        if self._window_end:
            outp = self.decoder.decode_spikes(self._output_buffer)
            ## Remove this after testing
            # print(f"Decoding output")
            # outp = self._output_buffer.sum(axis=1)
            ##
            # Reset window start
            self._window_start = True

        self._decoder_called = True

        return outp

    def reset(self):
        self._clear_buffer()
        self._counter = 0
        self._window_start = True
        self._window_end = False
        self._encoder_called = False
        self._decoder_called = False

    def _clear_buffer(self):
        self._input_buffer.fill(0)
        self._output_buffer.fill(0)

    def _validate_input(self, inp):
        if hasattr(inp, "__len__"):
            assert len(inp) == self.encoder.n_channels, f"Input length mismatch. Got {len(inp)}. Expected {self.encoder.n_channels}"
        else:
            assert self.encoder.n_channels == 1, f"Input size must be 1. Got input value={inp}"

    @property
    def ready(self):
        return self._window_end

    @property
    def input_size(self):
        return self._input_neurons

    @property
    def output_size(self):
        return self._output_neurons

    @property
    def window_size(self):
        return self._window_size


class SpikeCoderEnvWrapper(CompositeSpikeCoder):
    def __init__(self, observation_space: gym.Space, action_space: gym.Space, window_size: int, *, 
                 encoding_method: Literal["single", "multi", "rate", "temporal"] = 'single',
                encoder_params: dict = {},
                decoding_method: Literal["voting", "weighted-voting", "rate", "rate-div", "temporal", "ttfs"] = 'voting',
                decoder_params: dict = {}
                ):
        self._obs_space = observation_space
        self._action_space = action_space

        input_channels, n_neurons, low, high, dtype = self.get_env_info(self._obs_space)
        encoder_params.update(dict(lower_bounds=low, upper_bounds=high))
        if n_neurons is not None:
            encoder_params.update(dict(n_neurons=n_neurons))
        output_channels, n_neurons, low, high, dtype = self.get_env_info(self._action_space)
        decoder_params.update(dict(lower_bounds=low, upper_bounds=high, output_type=dtype))
        if dtype == "discrete" and n_neurons is not None:
            decoder_params.update(dict(in_neurons=n_neurons))

        super().__init__(input_channels, output_channels, window_size, 
                         encoding_method=encoding_method, encoder_params=encoder_params, 
                         decoding_method=decoding_method, decoder_params=decoder_params)

    def get_env_info(self, space: gym.Space) -> Tuple[int, int, ArrayLike, ArrayLike, str]:
        if isinstance(space, gym.spaces.Box):
            n_channels = sum(space.shape)
            n_neurons = None
            lower_bounds = space.low
            upper_bounds = space.high
            dtype = "continuous"
        elif isinstance(space, gym.spaces.Discrete):
            n_channels = 1
            n_neurons = space.n
            lower_bounds = np.zeros((n_channels, ), dtype=int)
            upper_bounds = np.full((n_channels, ), fill_value=space.n-1)
            dtype = "discrete"
        elif isinstance(space, gym.spaces.MultiDiscrete):
            n_channels = sum(space.shape)
            n_neurons = space.nvec
            lower_bounds = np.zeros((n_channels, ), dtype=int)
            upper_bounds = np.asarray(space.nvec) - 1
            dtype = "discrete"
        else:
            raise ValueError(f"Space type {type(space)} not yet supported. Please use CompositeSpikeCoder class directly")
        return n_channels, n_neurons, lower_bounds, upper_bounds, dtype


#### Encoder ####

class BaseSpikeEncoder(ABC):
    def __init__(self, n_channels: int, n_neurons: int | Sequence[int], window_size: int, 
                 lower_bounds: Sequence | np.ndarray, upper_bounds: Sequence | np.ndarray,
                 side: str = "left"):
        self.n_channels = n_channels
        if isinstance(n_neurons, int | np.int_):
            self._n_neurons = [n_neurons for _ in range(self.n_channels)]
            self._unequal_neurons = False
        elif isinstance(n_neurons, Sequence | np.ndarray):
            assert len(n_neurons) == self.n_channels
            self._n_neurons = [n for n in n_neurons]
            self._unequal_neurons = True
        else:
            raise ValueError(f"'n_neurons' must either be an int or ArrayLike. Got type {type(n_neurons)}")
        self._n_neurons = np.asarray(self._n_neurons)
        self._total_neurons = sum(self._n_neurons)
        # Starting index position for each channel after flattening neuron id
        self._cumu_index = np.cumsum([0, *(self._n_neurons[:-1])])

        self.window_size = window_size
        assert len(lower_bounds) == self.n_channels
        self.lower_bounds = lower_bounds
        assert len(upper_bounds) == self.n_channels
        self.upper_bounds = upper_bounds

        self._side = str(side).lower()
        assert self._side in ("left", "right")
        self._side_left = side == "left"
        self._side_right = side == "right"

        self._empty_array = np.zeros((self._total_neurons, self.window_size), dtype=np.int8)
        self._bins = [np.linspace(lw, hg, n+1) for lw, hg, n in \
                      zip(self.lower_bounds, self.upper_bounds, self._n_neurons)]

    # def _get_neuron_index(self, inp):
    #     """
    #     Get index of corresponding neuron for each channel based on defined bins

    #     Args:
    #         inp (_type_): _description_
    #     """
    #     idx = [np.searchsorted(bin_i, xi, side=self._side) - 1 \
    #             for xi, bin_i in zip(inp, self._bins)]
    #     return np.clip(idx, 0, self._n_neurons-1) # To ensure valid neuron index and
    #                                               # and prevent overflowing

    def _get_neuron_index(self, inp: np.ndarray, calc_scale: bool = True) -> Tuple[np.ndarray, np.ndarray]:
        """
        Get index of corresponding neuron for each channel based on defined bins, 
        along with scale between [0, 1] of where the value lie within that bin

        Args:
            inp: np.ndarray
                Input values with same length as channel
            calc_scale: bool
                Whether or not to calculate the scale
        """
        idx = np.zeros(self.n_channels, dtype=int)
        if calc_scale:
            scale = np.empty(self.n_channels, dtype=float)
        else:
            scale = None
        for i, (xi, bin_i) in enumerate(zip(inp, self._bins)):
            for j in range(1, self._n_neurons[i]+1):
                if self._side_left and (bin_i[j-1] < xi <= bin_i[j]) or \
                    self._side_right and (bin_i[j-1] <= xi < bin_i[j]):
                    idx[i] = j - 1
                    if calc_scale:
                        scale[i] = (xi - bin_i[j-1]) / (bin_i[j] - bin_i[j-1])
                    break
        return idx, scale

    def generate_spikes(self, inp: np.ndarray) -> np.ndarray:
        assert inp.ndim == 1, f"Parallen input encoding not yet supported. Input length must be 1-dimension of the same length as n_channels={self.n_channels}"
        assert inp.size == self.n_channels, f"Input must have the same length as encoded channels {self.n_channels}. Got input length: {inp.size}"
        return self._empty_array.copy()

    @property
    def bins(self):
        return self._bins

    @property
    def neuron_size(self):
        return self._total_neurons


class SingleSpikeEncoder(BaseSpikeEncoder):
    def generate_spikes(self, inp: np.ndarray) -> np.ndarray:
        out_array = super().generate_spikes(inp)

        # Find bin index of each input value and convert to flattened index
        neuron_idx, _ = self._get_neuron_index(inp, calc_scale=False)
        flat_neuron_idx = np.asarray(neuron_idx) + self._cumu_index
        out_array[flat_neuron_idx, 0] = 1
        return out_array


class TemporalEncoder(BaseSpikeEncoder):
    def generate_spikes(self, inp):
        out_array = super().generate_spikes(inp)

        # Find bin index of each input value and convert to flattened index
        neuron_idx, scale = self._get_neuron_index(inp, calc_scale=True)
        spk_loc = (scale * self.window_size).astype(int)
        flat_neuron_idx = np.asarray(neuron_idx) + self._cumu_index
        out_array[flat_neuron_idx, spk_loc] = 1
        return out_array


class MultiSpikeEncoder(BaseSpikeEncoder):
    def generate_spikes(self, inp):
        out_array = super().generate_spikes(inp)

        # Find bin index of each input value and convert to flattened index
        neuron_idx, scale = self._get_neuron_index(inp, calc_scale=True)
        spk_loc = (scale * self.window_size).astype(int)
        flat_neuron_idx = np.asarray(neuron_idx) + self._cumu_index
        for idx, loc in zip(flat_neuron_idx, spk_loc):
            out_array[idx, :loc] = 1
        return out_array


class RateEncoder(BaseSpikeEncoder):
    def generate_spikes(self, inp):
        out_array = super().generate_spikes(inp)

        # Find bin index of each input value and convert to flattened index
        neuron_idx, scale = self._get_neuron_index(inp, calc_scale=True)
        flat_neuron_idx = np.asarray(neuron_idx) + self._cumu_index
        for idx, sc in zip(flat_neuron_idx, scale):
            out_array[idx, :] = np.random.binomial(1, p=sc, size=(self.window_size,))
        return out_array


# ------------------------------------------------ #
#### Decoder ####

class BaseSpikeDecoder(ABC):
    _total_neurons: int
    out_channels: int
    window_size: int

    def __init__(self, out_channels: int, window_size: int, output_type: Literal["discrete", "continuous"]):
        super().__init__()
        self.out_channels = int(out_channels)
        self.window_size = int(window_size)
        self._total_neurons = self.out_channels
        self._output_type = str(output_type).lower()
        assert self._output_type in ("discrete", "continuous"), f"Invalid Output type. Got {self._output_type}"
        self._is_discrete = self._output_type == "discrete"
        self._is_continuous = self._output_type == "continuous"

    @abstractmethod
    def decode_spikes(self, spikes: np.ndarray) -> np.ndarray:
        pass

    @property
    def neuron_size(self) -> int:
        return self._total_neurons

    @property
    def output_type(self) -> Literal["discrete", "continuous"]:
        return self._output_type
    @output_type.setter
    def output_type(self, value: Literal["discrete", "continuous"]):
        value = str(value).lower()
        if value == "discrete":
            self._output_type = value
            self._is_discrete = True
            self._is_continuous = False
        elif value == "continuous":
            self._output_type = value
            self._is_discrete = False
            self._is_continuous = True
        else:
            raise ValueError(f"Invalid Output type. Got {value}")

    def is_discrete(self) -> bool:
        return self._is_discrete
    def is_continuous(self) -> bool:
        return self._is_continuous


class OneToOneSpikeDecoder(BaseSpikeDecoder, ABC):
    def __init__(self, out_channels: int, window_size: int,
                 lower_bounds: Sequence | np.ndarray, upper_bounds: Sequence | np.ndarray,
                 output_type: Literal["discrete", "continuous"]):
        super().__init__(out_channels, window_size, output_type)

        assert len(lower_bounds) == self.out_channels, "Lower Bounds must be the of same length as output channels"
        self.lower_bounds = np.asarray(lower_bounds)
        assert len(upper_bounds) == self.out_channels, "Upper Bounds must be the of same length as output channels"
        self.upper_bounds = np.asarray(upper_bounds)
        assert np.all(self.upper_bounds > self.lower_bounds), "Upper Bounds must be strictly greater than Lower Bounds"

    def decode_spikes(self, spikes):
        assert spikes.shape == (self._total_neurons, self.window_size)
        outp = self._calculate_output(spikes)
        if self.is_discrete():
            outp = np.astype(outp, dtype=int)
            if self.out_channels == 1:
                outp = outp.item()
        return outp

    @abstractmethod
    def _calculate_output(self, spikes):
        pass


class RateDivDecoder(OneToOneSpikeDecoder):
    def __init__(self, out_channels: int, window_size: int, n_classes: int, rate_division: int | float = None,
                 lower_bounds: Sequence | np.ndarray = None, upper_bounds: Sequence | np.ndarray = None,
                 output_type: Literal["discrete", "continuous"] = "discrete",):
        self.n_classes = int(n_classes)
        if lower_bounds is None:
            lower_bounds = np.zeros((out_channels, ), dtype=int)
        if upper_bounds is None:
            upper_bounds = np.full((out_channels, ), fill_value=n_classes-1, dtype=int)
        super().__init__(out_channels, window_size, lower_bounds, upper_bounds, output_type=output_type)
        self.rate_division = rate_division if rate_division is not None else \
            self.window_size / self.n_classes
        assert self.rate_division > 0, f"Rate division must be a positive integer. Got {self.rate_division}"

    def _calculate_output(self, spikes: np.ndarray):
        agg = spikes.sum(axis=1)
        agg = agg / self.rate_division
        agg = np.round(agg).astype(int)
        outp = np.clip(agg, self.lower_bounds, self.upper_bounds)
        return outp


class RateDecoder(OneToOneSpikeDecoder):
    def __init__(self, out_channels: int, window_size: int,
                 lower_bounds: Sequence | np.ndarray, upper_bounds: Sequence | np.ndarray,
                 output_type: Literal["discrete", "continuous"] = "continuous",):
        super().__init__(out_channels, window_size, lower_bounds, upper_bounds, output_type)

    def _calculate_output(self, spikes: np.ndarray):
        agg = spikes.sum(axis=1)
        agg = agg / self.window_size
        outp = self.lower_bounds + agg * (self.upper_bounds - self.lower_bounds)
        return outp


class TemporalDecoder(OneToOneSpikeDecoder):
    def __init__(self, out_channels, window_size, lower_bounds, upper_bounds,
                 output_type: Literal["discrete", "continuous"] = "continuous",):
        super().__init__(out_channels, window_size, lower_bounds, upper_bounds, output_type)

    def _calculate_output(self, spikes: np.ndarray):
        ttfs = self._aggregate(spikes)
        ttfs = ttfs / self.window_size
        scaled_vals = self.lower_bounds + ttfs * (self.upper_bounds - self.lower_bounds)
        outp = np.where(np.isinf(ttfs), self.upper_bounds, scaled_vals)
        return outp
    
    def _aggregate(self, spikes: np.ndarray):
        return np.where(np.sum(spikes, axis=1) == 0, np.inf, np.argmax(spikes, axis=1))


class ManyToOneSpikeDecoder(BaseSpikeDecoder, ABC):
    def __init__(self, out_channels: int, in_neurons: int | Sequence[int], window_size: int, 
                 output_type: Literal["discrete", "continuous"],
                 lower_bounds: Sequence | np.ndarray, upper_bounds: Sequence | np.ndarray,):
        super().__init__(out_channels, window_size, output_type)
        # self.out_channels = out_channels
        # self.in_neurons = in_neurons

        if isinstance(in_neurons, int | np.int_):
            self.in_neurons = [in_neurons for _ in range(self.out_channels)]
            self._unequal_neurons = False
        elif isinstance(in_neurons, Sequence | np.ndarray):
            assert len(in_neurons) == self.out_channels
            self.in_neurons = [n for n in in_neurons]
            self._unequal_neurons = True
        else:
            raise ValueError(f"'n_neurons' must either be an int or ArrayLike. Got type {type(in_neurons)}")
        self.in_neurons = np.asarray(self.in_neurons)
        self._total_neurons = sum(self.in_neurons)
        # Starting index position for each channel after flattening neuron id
        self._start_index = np.cumsum([0, *(self.in_neurons[:-1])])

        # self.window_size = int(window_size)

        if lower_bounds is not None:
            assert len(lower_bounds) == self.out_channels
            self.lower_bounds = np.asarray(lower_bounds)
        else:
            # raise ValueError(f"'lower_bounds' must be specified")
            self.lower_bounds = np.zeros(self.out_channels)

        if upper_bounds is not None:
            assert len(upper_bounds) == self.out_channels
            self.upper_bounds = np.asarray(upper_bounds)
        else:
            # raise ValueError(f"'upper_bounds' must be specified")
            self.upper_bounds = np.array([n-1 for n in self.in_neurons])

        self._neuron_values = [np.linspace(lw, hg, num=n) \
                               for lw, hg, n in zip(self.lower_bounds, self.upper_bounds, self.in_neurons)]
        if self.output_type == "discrete":
            self._neuron_values = [vals.astype(int) for vals in self._neuron_values]

    def decode_spikes(self, spikes: np.ndarray):
        assert spikes.shape == (self._total_neurons, self.window_size)
        outp = self._calculate_output(spikes)
        if self.is_discrete():
            outp = np.astype(outp, int)
            if self.out_channels == 1:
                outp = outp.item()
        return outp

    def _calculate_output(self):
        pass
    

class SingleVotingDecoder(ManyToOneSpikeDecoder):
    def __init__(self, out_channels: int, in_neurons: int | Sequence[int], window_size: int, 
                 output_type: Literal["discrete", "continuous"] = "continuous",
                 lower_bounds: Sequence | np.ndarray = None, upper_bounds: Sequence | np.ndarray = None,
                ):
        super().__init__(out_channels, in_neurons, window_size, output_type=output_type, 
                         lower_bounds=lower_bounds, upper_bounds=upper_bounds)

    # def decode_spikes(self, spikes: np.ndarray):
    #     assert spikes.shape == (self._total_neurons, self.window_size)
    #     outp = self._calculate_output(spikes)
    #     # outp = [np.take(vals, ix) for vals, ix in zip(self._neuron_values, voted_idx)]
    #     return np.asarray(outp)

    def _calculate_output(self, spikes: np.ndarray) -> ArrayLike:
        agg = self._aggregate(spikes)

        outp = np.zeros((self.out_channels, ), dtype=np.int32 if self.is_discrete() else np.float64)
        for n, vals in zip(range(self.out_channels), self._neuron_values):
            if n < self.out_channels - 1:
                section = agg[self._start_index[n]: self._start_index[n+1]]
            else:
                section = agg[self._start_index[n]: ]
            voted_idx = np.where(section == max(section))[0]
            if len(voted_idx) > 1:
                voted_idx = np.random.choice(voted_idx)
            outp[n] = vals[voted_idx]
        return outp

    def _aggregate(self, spikes: np.ndarray):
        return spikes.sum(axis=1)


class WeightedVotingDecoder(ManyToOneSpikeDecoder):
    def __init__(self, out_channels: int, in_neurons: int | Sequence[int], window_size: int, 
                 output_type: Literal["discrete", "continuous"] = "continuous",
                 lower_bounds: Sequence | np.ndarray = None, upper_bounds: Sequence | np.ndarray = None,):
        super().__init__(out_channels, in_neurons, window_size, output_type, lower_bounds, upper_bounds)

    # def decode_spikes(self, spikes: np.ndarray):
    #     assert spikes.shape == (self._total_neurons, self.window_size)
    #     outp = self._calculate_output(spikes)
    #     return np.asarray(outp)

    def _calculate_output(self, spikes: np.ndarray) -> ArrayLike:
        agg = spikes.sum(axis=1)

        outp = np.zeros((self.out_channels, ), dtype=np.float64)
        for n, vals in zip(range(self.out_channels), self._neuron_values):
            if n < self.out_channels - 1:
                section_count = agg[self._start_index[n]: self._start_index[n+1]]
            else:
                section_count = agg[self._start_index[n]: ]
            wg_val = sum(section_count * vals) / sum(section_count)
            outp[n] = wg_val
        return outp


class TimeToFirstSpikeDecoder(ManyToOneSpikeDecoder):
    def __init__(self, out_channels: int, in_neurons: int | Sequence[int], window_size: int, 
                 output_type: Literal["discrete", "continuous"] = "continuous",
                 lower_bounds: Sequence | np.ndarray = None, upper_bounds: Sequence | np.ndarray = None,):
        super().__init__(out_channels, in_neurons, window_size, output_type, lower_bounds, upper_bounds)

    # def decode_spikes(self, spikes: np.ndarray):
    #     assert spikes.shape == (self._total_neurons, self.window_size)
    #     outp = self._calculate_output(spikes)
    #     return np.asarray(outp)

    def _calculate_output(self, spikes: np.ndarray) -> ArrayLike:
        agg = self._aggregate(spikes)

        outp = np.zeros((self.out_channels, ), dtype=np.float64)
        for n, vals in zip(range(self.out_channels), self._neuron_values):
            if n < self.out_channels - 1:
                section = agg[self._start_index[n]: self._start_index[n+1]]
            else:
                section = agg[self._start_index[n]: ]
            voted_idx = np.where(section == min(section))[0]
            if len(voted_idx) > 1:
                voted_idx = np.random.choice(voted_idx)
            outp[n] = vals[int(voted_idx)]
        return outp

    def _aggregate(self, spikes: np.ndarray):
        agg = np.where(np.sum(spikes, axis=1) == 0, np.inf, np.argmax(spikes, axis=1))
        return agg

