"""
2026-08-03

Spike Encoding / Decoding Schemes. 

Based on system in:
Schuman, C., Rizzo, C., McDonald-Carmack, J., Skuda, N., & Plank, J. (2022). 
Evaluating Encoding and Decoding Approaches for Spiking Neuromorphic Systems. 
Proceedings of the International Conference on Neuromorphic Systems 2022, 1–9. 
https://doi.org/10.1145/3546790.3546792

"""

import sys
from abc import ABC, abstractmethod
from typing import Literal, Sequence

import numpy as np
from numpy.typing import ArrayLike
import gymnasium as gym

from common.base import SpikeCoder


ENCODER_DICT = {
    "single": 'SingleSpikeEncoder'
}

DECODER_DICT = {
    "voting": 'SingleVotingDecoder'
}


def create_spike_encoder(method: str, **kwargs):
    method = str(method).lower()
    if method not in ENCODER_DICT:
        raise ValueError(f"Encoder type: {method} not found in supported spike encoding methods")
    clss_name = ENCODER_DICT.get(method)
    clss = getattr(sys.modules[__name__], clss_name)
    return clss(**kwargs)

def create_spike_decoder(method: str, **kwargs):
    method = str(method).lower()
    if method not in DECODER_DICT:
        raise ValueError(f"Decoder type: {method} not found in supported spike decoding methods")
    clss_name = DECODER_DICT.get(method)
    clss = getattr(sys.modules[__name__], clss_name)
    return clss(**kwargs)


class NewSpikeCoder(SpikeCoder, ABC):
    def __init__(self, input_channels, output_channels, window_size, *,
                 encoding_method: Literal["single", "multi", "rate", "temporal"] = 'single',
                 encoder_params: dict = {},
                 decoding_method: Literal["voting", "weighted-voting", "rate", "rate-div", "temporal", "ttfs"] = 'voting',
                 decoder_params: dict = {},
                 n_neurons_in=1, 
                 n_neurons_out=None,
                 
                 ):
        super().__init__()
        self.window_size = window_size

        encoder_params["window_size"] = self.window_size
        decoder_params["window_size"] = self.window_size

        # Create separate Encoder and Decoder based on specifications
        self.encoder: BaseSpikeEncoder = create_spike_encoder(method=encoding_method, **encoder_params)
        self.decoder: BaseSpikeDecoder = create_spike_decoder(method=decoding_method, **decoder_params)


        self._input_neurons = self.encoder.neuron_size
        self._output_neurons = self.decoder.neuron_size

        ## Remove this after testing
        # self.window_size = window_size
        # self._input_neurons = input_channels
        # self._output_neurons = output_channels
        ##

        # Buffer to store encoded spike train to give network at each timestep (input buffer)
        #   and to record spikes generated by network for decoding at end of window (output buffer)
        self._input_buffer = np.zeros((self._input_neurons, self.window_size), dtype=np.int8)
        self._output_buffer = np.zeros((self._output_neurons, self.window_size), dtype=np.int8)

        # Step counter within window
        self._counter = 0

        # Flags and controls for effective flow
        self._window_start = True
        self._window_end = False
        self._encoder_called = False
        self._decoder_called = False

    def encode(self, inp: int | np.ndarray):
        # Control proper flow of encoder-decoder
        if (not self._decoder_called) and not self._window_start:
            raise RuntimeError("Decoder must be called before calling Encoder, unless it's a new window")
        self._decoder_called = False

        # If previous window just ended, clear buffer and reset counter
        if self._window_start:
            self._clear_buffer()
            self._counter = 0
            self._window_end = False

        # At beginning of window, encoder input values into spike trains, 
        #   then store in input buffer
        if self._window_start:
            self._validate_input(inp)
            spk_train = self.encoder.generate_spikes(inp)
            ## Remove this after testing
            # print(f"Encoding inputs {inp}")
            # spk_train = np.zeros((self._input_neurons, self.window_size), dtype=np.int8)
            # spk_train[::2, ::2] = 1
            # spk_train[1::2, 1::2] = 1
            ##
            self._input_buffer = spk_train
            self._window_start = False

        self._encoder_called = True

        return self._input_buffer[:, self._counter]

    def decode(self, spikes: np.ndarray) -> None | np.ndarray | int | float:
        # Control proper flow of encoder-decoder
        if not self._encoder_called:
            raise RuntimeError("Encoder must be called before calling Decoder")
        self._encoder_called = False

        # If still within window, record spikes onto output buffer
        if not self._window_end:
            # Record spikes
            self._output_buffer[:, self._counter] = spikes

        # Increment counter and check for end of window
        self._window_end = self._counter >= (self.window_size - 1)
        self._counter += 1

        # If window has ended, decode the output buffer into output values
        outp = None
        if self._window_end:
            outp = self.decoder.decode_spikes(self._output_buffer)
            ## Remove this after testing
            # print(f"Decoding output")
            # outp = self._output_buffer.sum(axis=1)
            ##
            # Reset window start
            self._window_start = True

        self._decoder_called = True

        return outp

    def reset(self):
        self._clear_buffer()
        self._counter = 0
        self._window_start = True
        self._window_end = False
        self._encoder_called = False
        self._decoder_called = False

    def _clear_buffer(self):
        self._input_buffer.fill(0)
        self._output_buffer.fill(0)

    def _validate_input(self, inp):
        assert len(inp) == self.encoder.n_channels

    @property
    def ready(self):
        return self._window_end

    @property
    def input_size(self):
        return self._input_neurons

    @property
    def output_size(self):
        return self._output_neurons


#### Encoder ####

class BaseSpikeEncoder(ABC):
    def __init__(self, n_channels: int, n_neurons: int | Sequence[int], window_size: int, 
                 lower_bounds: Sequence | np.ndarray, upper_bounds: Sequence | np.ndarray,
                 side: str = "left"):
        self.n_channels = n_channels
        if isinstance(n_neurons, int):
            self._n_neurons = [n_neurons for _ in range(self.n_channels)]
            self._unequal_neurons = False
        elif isinstance(n_neurons, Sequence) or isinstance(n_neurons, np.ndarray):
            assert len(n_neurons) == self.n_channels
            self._n_neurons = [n for n in n_neurons]
            self._unequal_neurons = True
        else:
            raise ValueError(f"'n_neurons' must either be an int or ArrayLike. Got type {type(n_neurons)}")
        self._n_neurons = np.asarray(self._n_neurons)
        self._total_neurons = sum(self._n_neurons)
        # Starting index position for each channel after flattening neuron id
        self._cumu_index = np.cumsum([0, *(self._n_neurons[:-1])])

        self.window_size = window_size
        assert len(lower_bounds) == self.n_channels
        self.lower_bounds = lower_bounds
        assert len(upper_bounds) == self.n_channels
        self.upper_bounds = upper_bounds

        self._side = side

        self._empty_array = np.zeros((self._total_neurons, self.window_size), dtype=np.int8)
        self._bins = [np.linspace(lw, hg, n+1) for lw, hg, n in \
                      zip(self.lower_bounds, self.upper_bounds, self._n_neurons)]

    def _get_neuron_index(self, inp):
        """
        Get index of corresponding neuron for each channel based on defined bins

        Args:
            inp (_type_): _description_
        """
        idx = [np.searchsorted(bin_i, xi, side=self._side) - 1 \
                for xi, bin_i in zip(inp, self._bins)]
        return np.clip(idx, 0, self._n_neurons-1) # To ensure valid neuron index and
                                                  # and prevent overflowing

    @abstractmethod
    def generate_spikes(self, inp: np.ndarray) -> np.ndarray:
        pass

    @property
    def bins(self):
        return self._bins

    @property
    def neuron_size(self):
        return self._total_neurons


class SingleSpikeEncoder(BaseSpikeEncoder):
    def generate_spikes(self, inp):
        out_array = self._empty_array.copy()

        # Find bin index of each input value and convert to flattened index
        neuron_idx = self._get_neuron_index(inp)
        flat_neuron_idx = np.asarray(neuron_idx) + self._cumu_index
        out_array[flat_neuron_idx, 0] = 1
        return out_array


#### Decoder ####

class BaseSpikeDecoder(ABC):
    def __init__(self, out_channels, in_neurons, window_size, lower_bounds=None, upper_bounds=None):
        self.out_channels = out_channels
        # self.in_neurons = in_neurons

        if isinstance(in_neurons, int):
            self.in_neurons = [in_neurons for _ in range(self.out_channels)]
            self._unequal_neurons = False
        elif isinstance(in_neurons, Sequence) or isinstance(in_neurons, np.ndarray):
            assert len(in_neurons) == self.out_channels
            self.in_neurons = [n for n in in_neurons]
            self._unequal_neurons = True
        else:
            raise ValueError(f"'n_neurons' must either be an int or ArrayLike. Got type {type(in_neurons)}")
        self.in_neurons = np.asarray(self.in_neurons)
        self._total_neurons = sum(self.in_neurons)
        # Starting index position for each channel after flattening neuron id
        self._start_index = np.cumsum([0, *(self.in_neurons[:-1])])

        self.window_size = int(window_size)

        if lower_bounds is not None:
            assert len(lower_bounds) == self.out_channels
            self.lower_bounds = np.asarray(lower_bounds)
        else:
            self.lower_bounds = np.zeros(self.out_channels)

        if upper_bounds is not None:
            assert len(upper_bounds) == self.out_channels
            self.upper_bounds = np.asarray(upper_bounds)
        else:
            self.upper_bounds = np.array([n-1 for n in self.in_neurons])

        self._neuron_values = [np.linspace(lw, hg, num=n) \
                               for lw, hg, n in zip(self.lower_bounds, self.upper_bounds, self.in_neurons)]

    @abstractmethod
    def decode_spikes(self, spikes: np.ndarray) -> np.ndarray:
        pass

    @property
    def neuron_size(self):
        return self._total_neurons


class SingleVotingDecoder(BaseSpikeDecoder):
    def __init__(self, out_channels: int, in_neurons: int | Sequence[int], window_size: int, 
                 lower_bounds: Sequence | np.ndarray = None, upper_bounds: Sequence | np.ndarray = None,
                ):
        super().__init__(out_channels, in_neurons, window_size, lower_bounds, upper_bounds)

    def decode_spikes(self, spikes: np.ndarray):
        assert spikes.shape == (self._total_neurons, self.window_size)
        voted_idx = self._get_voted_index(spikes)
        outp = [np.take(vals, ix) for vals, ix in zip(self._neuron_values, voted_idx)]
        return np.asarray(outp)

    def _get_voted_index(self, spikes: np.ndarray) -> ArrayLike:
        agg = spikes.sum(axis=1)

        outp = np.zeros((self.out_channels, ), dtype=int)
        for n in range(self.out_channels):
            if n < self.out_channels - 1:
                section = agg[self._start_index[n]: self._start_index[n+1]]
            else:
                section = agg[self._start_index[n]: ]
            # TODO: deal with ties
            outp[n] = np.argmax(section)
        return outp

