num_sim_steps: 2000
pattern_params:
  type: poisson
  duration: 10
  rate: 100
  dt: 0.001
  num_classes: 2
  num_sets: 10
spikegen_params:
  class: CustomTimingGenerator
  binary: false
  spacing: 0
  jitter_std: 0.0
  failure_rate: 0.0
  randomise_class: true
snn_params:
  input_size: 5
  hidden_size: 0
  output_size: 2
  dt: 0.001
  neuron_params:
    tau_mem: 0.004
    tau_trace: 0.004
  synapse_params:
    clip_weights: false
    normalise_weights: false
    normalise_method: L2
    eligibility_trace: true
    tau_syn: 0.015
  winner_take_all: false
  soft_reset: true
# rewarder_params:
#   type: weighted
#   ignore_silent_inputs: false
#   log_scale: false
# collector_params:
#   type: simple
#   fitness_type: reward
#   agg_func: sum
decoder_params:
  type: rate
  # type: final
  # direction: last
  # convert_type: negate
  reward_null: 0.0
  reward_correct: 1.0
  reward_incorrect: -1.0
fitnessor_params:
  type: reward
  # type: accuracy
  # type: cross_entropy
  # type: mse
arule_params:
  learning_rate: 0.1
  hidden_size: 4
  bias: true
  hidden_activation: relu
  output_activation: tanh
  use_weights: true
  use_reward: true
  use_trace_pre: false
  use_trace_post: false
  use_eligibility: true
evo_params:
  manager:
    type: original
    max_generations: 200
    tolerance: 0.02
    num_trials: 10
    save_best: 3
    record_classes: true
  solver:
    # ndim: 25
    type: CMA-ES
    popsize: 30
    # minimise: false
  evaluator:
    update_inputs: true
    # record_classes: true